version: 0.2
 
phases:
  install:
    runtime-versions:
      java: corretto8
      docker: 18
  pre_build:
    commands:
      - echo "Pre_build"
      - echo "Logging in to Amazon ECR"
      - $(aws ecr get-login  --no-include-email --region us-east-1)
  build:
    commands:
      - echo "Build"
      - echo "Entered build phase"
      - echo "Building Java"
      - cd  DrugMicroservice-master
      - mvn clean package
      - docker build -t drug-2143886-registry .
      - docker tag drug-2143886-registry:latest 555918697305.dkr.ecr.ap-south-1.amazonaws.com/drug-2143886-registry:latest
 
  post_build:
    commands:
      - echo "Post_build"
      - docker push 555918697305.dkr.ecr.ap-south-1.amazonaws.com/drug-2143886-registry:latest
      - printf '[{"name":"drug-2143886-registry","imageUri":"%s"}]' 555918697305.dkr.ecr.ap-south-1.amazonaws.com/drug-2143886-registry:latest > taskdefinition.json
      - cat taskdefinition.json
 
artifacts:
  files:
    - DrugMicroservice-master/taskdefinition.json